---
apiVersion: v1
kind: Namespace
metadata:
  name: tor-proxy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: tor-proxy
  name: tor-proxy-deployment
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: tor-proxy
  replicas: 5
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tor-proxy
    spec:
      containers:
      - image: dperson/torproxy
        imagePullPolicy: Always
        name: tor-proxy
        ports:
        - containerPort: 8118

---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: tor-proxy
  name: tor-proxy-service
  namespace: tor-proxy
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb-ip
spec:
  ports:
    - port: 18118
      #nodePort: 30118
      targetPort: 8118
    # socks
    # - port: 19050
      #nodePort: 39050
      # targetPort: 9050
      protocol: TCP
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: tor-proxy
