---
apiVersion: v1
kind: Namespace
metadata:
  name: tor-proxy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: tor-proxy
  name: tor-proxy-deployment
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: tor-proxy
  replicas: 5
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tor-proxy
    spec:
      containers:
      - image: dperson/torproxy
        imagePullPolicy: Always
        name: tor-proxy
        ports:
        - containerPort: 8118

---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: tor-proxy
  name: tor-proxy-service
  namespace: tor-proxy
spec:
  ports:
    - port: 18118
      #nodePort: 30118
      targetPort: 8118
    # socks
    # - port: 19050
      #nodePort: 39050
      # targetPort: 9050
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: tor-proxy
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: tor-proxy
  name: tor-proxy-ingress
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 18118}]'
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: tor-proxy-service
              servicePort: 18118